package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/Limetric/hostmux/internal/config"
	"github.com/Limetric/hostmux/internal/hostnames"
)

type initOptions struct {
	ConfigPath string
	Domain     string
	Listen     string
	HidePort   bool
	Tunnel     bool
	Force      bool
	Writer     io.Writer
}

// generateConfigTemplate renders a commented, valid hostmux config from the
// chosen domain, listen address, and hide_port. The result is intentionally
// minimal so it always passes `hostmux config check`; advanced blocks are
// included as comments for discoverability.
func generateConfigTemplate(domain, listen string, hidePort bool) string {
	var b strings.Builder
	b.WriteString("# hostmux configuration — generated by `hostmux init`\n")
	b.WriteString("# Docs: https://github.com/Limetric/hostmux\n\n")
	fmt.Fprintf(&b, "domain = %q\n", domain)
	fmt.Fprintf(&b, "listen = %q\n", listen)
	fmt.Fprintf(&b, "hide_port = %t\n", hidePort)
	b.WriteString("\n# Per-request access logs (optional):\n")
	b.WriteString("# access_log = true\n")
	b.WriteString("# log_format = \"text\"   # or \"json\"\n")
	b.WriteString("\n# Override the managed self-signed certificate (optional):\n")
	b.WriteString("# [tls]\n")
	b.WriteString("# cert = \"~/certs/hostmux.crt\"\n")
	b.WriteString("# key = \"~/certs/hostmux.key\"\n")
	b.WriteString("\n# Proxy hardening (optional):\n")
	b.WriteString("# [proxy]\n")
	b.WriteString("# read_header_timeout = \"10s\"\n")
	b.WriteString("# response_header_timeout = \"30s\"\n")
	b.WriteString("\n# Persistent routes (hot-reloaded on save):\n")
	b.WriteString("# [[app]]\n")
	b.WriteString("# hosts = [\"api\"]\n")
	b.WriteString("# upstream = \"http://127.0.0.1:8080\"\n")
	return b.String()
}

func runInit(opts initOptions) error {
	w := opts.Writer
	if w == nil {
		w = os.Stdout
	}

	path := opts.ConfigPath
	if path == "" {
		path = defaultConfigPath()
	}
	if path == "" {
		return exitError{code: 2, text: "hostmux init: could not determine a config path; pass --config"}
	}

	domain := hostnames.NormalizeDomain(opts.Domain)
	if domain == "" {
		domain = config.DefaultDomain
	}
	listen := opts.Listen
	if listen == "" {
		listen = config.DefaultTLSListen
	}
	if err := config.ValidateListenAddr(listen); err != nil {
		return exitError{code: 2, text: fmt.Sprintf("hostmux init: --listen: %v", err)}
	}

	// The tunnel workflow defaults hide_port on (cloudflared terminates
	// public TLS on 443, so printed URLs should omit the listener port).
	hidePort := opts.HidePort || opts.Tunnel

	if _, err := os.Stat(path); err == nil && !opts.Force {
		return exitError{code: 1, text: fmt.Sprintf("hostmux init: %s already exists; pass --force to overwrite", path)}
	} else if err != nil && !os.IsNotExist(err) {
		return exitError{code: 1, text: fmt.Sprintf("hostmux init: %v", err)}
	}

	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return exitError{code: 1, text: fmt.Sprintf("hostmux init: create config dir: %v", err)}
		}
	}

	content := generateConfigTemplate(domain, listen, hidePort)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return exitError{code: 1, text: fmt.Sprintf("hostmux init: write %s: %v", path, err)}
	}

	// Defensive: the generated file must be valid.
	if _, diags := config.Check(path); hasCheckError(diags) {
		return exitError{code: 1, text: fmt.Sprintf("hostmux init: generated config failed validation: %v", diags)}
	}

	fmt.Fprintf(w, "wrote %s\n", path)
	fmt.Fprintf(w, "  domain    = %s\n", domain)
	fmt.Fprintf(w, "  listen    = %s\n", listen)
	fmt.Fprintf(w, "  hide_port = %t\n", hidePort)

	// Warn about the localhost + non-443 case.
	if domain == "localhost" {
		if port, err := extractListenPort(listen); err == nil && port != 443 {
			fmt.Fprintf(w, "\nnote: domain is \"localhost\" on :%d; browsers expect https on :443.\n", port)
			fmt.Fprintln(w, "      See README \"HTTPS on port 443\" for unprivileged redirect patterns.")
		}
	}

	if opts.Tunnel {
		port := 8443
		if p, err := extractListenPort(listen); err == nil {
			port = p
		}
		fmt.Fprintln(w, "\ncloudflared ingress snippet:")
		fmt.Fprint(w, indentLines(renderCloudflareIngress(cloudflareParams{
			Domain:      domain,
			Port:        port,
			HTTPSOrigin: true,
			NoTLSVerify: true,
		}), "  "))
	}

	fmt.Fprintln(w, "\nNext: hostmux start")
	return nil
}

func hasCheckError(diags []config.Diagnostic) bool {
	for _, d := range diags {
		if d.Severity == config.SeverityError {
			return true
		}
	}
	return false
}

// indentLines prefixes every non-empty line with the given indent.
func indentLines(s, indent string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	var b strings.Builder
	for _, ln := range lines {
		if ln == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(indent)
		b.WriteString(ln)
		b.WriteString("\n")
	}
	return b.String()
}
